# Generated by Django 4.2.3 on 2023-07-21 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='verification_code',
            field=models.CharField(default=123123, max_length=6),
            preserve_default=False,
        ),
    ]
