# Generated by Django 4.2.3 on 2023-07-22 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_user_verification_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='activation_key_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
