# Generated by Django 4.2.3 on 2023-08-02 15:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(default=datetime.datetime(2023, 8, 2, 15, 37, 21, 810052, tzinfo=datetime.timezone.utc), upload_to='product/%Y-%m-%d/'),
            preserve_default=False,
        ),
    ]
