# Generated by Django 4.2.3 on 2023-07-22 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_user_activation_key_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='activation_key_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
