# Generated by Django 4.2.3 on 2023-07-22 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_user_activation_key_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='activation_key_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
