# Generated by Django 4.2.3 on 2023-07-22 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_user_activation_key_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='activation_key_time',
        ),
        migrations.AddField(
            model_name='user',
            name='activation_key_expires',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
